export const ASYNC_REGISTER_USER_SUCCESS = 'ASYNC_REGISTER_USER_SUCCESS';
export const ASYNC_REGISTER_USER_ERROR = 'ASYNC_REGISTER_USER_ERROR';
export const ASYNC_REGISTER_USER_REQUEST = 'ASYNC_REGISTER_USER_REQUEST';
