export const ASYNC_UPDATE_MOTORCYCLE_REQUEST = 'ASYNC_UPDATE_MOTORCYCLE_REQUEST';
export const ASYNC_UPDATE_MOTORCYCLE_SUCCESS = 'ASYNC_UPDATE_MOTORCYCLE_SUCCESS';
export const ASYNC_UPDATE_MOTORCYCLE_ERROR = 'ASYNC_UPDATE_MOTORCYCLE_ERROR';

export const ASYNC_ADD_MOTORCYCLE_REQUEST = 'ASYNC_ADD_MOTORCYCLE_REQUEST';
export const ASYNC_ADD_MOTORCYCLE_SUCCESS = 'ASYNC_ADD_MOTORCYCLE_SUCCESS';
export const ASYNC_ADD_MOTORCYCLE_ERROR = 'ASYNC_ADD_MOTORCYCLE_ERROR';
