export const ASYNC_CREATE_LOG_REQUEST = 'ASYNC_CREATE_LOG_REQUEST';
export const ASYNC_CREATE_LOG_ERROR = 'ASYNC_CREATE_LOG_ERROR';
export const ASYNC_CREATE_LOG_SUCCESS = 'ASYNC_CREATE_LOG_SUCCESS';

export const ASYNC_FETCH_LOGS_REQUEST = 'ASYNC_FETCH_LOGS_REQUEST';
export const ASYNC_FETCH_LOGS_ERROR = 'ASYNC_FETCH_LOGS_ERROR';
export const ASYNC_FETCH_LOGS_SUCCESS = 'ASYNC_FETCH_LOGS_SUCCESS';

export const ASYNC_UPDATE_LOGS_REQUEST = 'ASYNC_UPDATE_LOGS_REQUEST';
export const ASYNC_UPDATE_LOGS_ERROR = 'ASYNC_UPDATE_LOGS_ERROR';
export const ASYNC_UPDATE_LOGS_SUCCESS = 'ASYNC_UPDATE_LOGS_SUCCESS';

export const ASYNC_DELETE_LOG_REQUEST = 'ASYNC_DELETE_LOG_REQUEST';
export const ASYNC_DELETE_LOG_ERROR = 'ASYNC_DELETE_LOG_ERROR';
export const ASYNC_DELETE_LOG_SUCCESS = 'ASYNC_DELETE_LOG_SUCCESS';

export const CREATE_LOG = 'CREATE_LOG';
export const UPDATE_LOG_DATE = 'UPDATE_LOG_DATE';
export const ADD_LOG_MILES = 'ADD_LOG_MILES';
export const SELECT_LOG_PART = 'SELECT_LOG_PART';
export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_LOG_PART = 'DELETE_LOG_PART';
export const ADD_LOG_PART = 'ADD_LOG_PART';
export const EDIT_LOG = 'EDIT_LOG';
export const TOGGLE_MENU = 'TOGGLE_MENU';
