export const ASYNC_LOGIN_USER_SUCCESS = 'ASYNC_LOGIN_USER_SUCCESS';
export const ASYNC_LOGIN_USER_ERROR = 'ASYNC_LOGIN_USER_ERROR';
export const ASYNC_LOGIN_USER_REQUEST = 'ASYNC_LOGIN_USER_REQUEST';

export const ASYNC_LOGOUT_USER_SUCCESS = 'ASYNC_LOGOUT_USER_SUCCESS';
export const ASYNC_LOGOUT_USER_ERROR = 'ASYNC_LOGOUT_USER_ERROR';
export const ASYNC_LOGOUT_USER_REQUEST = 'ASYNC_LOGOUT_USER_REQUEST';

export const ASYNC_FETCH_USER_DATA_SUCCESS = 'ASYNC_FETCH_USER_DATA_SUCCESS';
export const ASYNC_FETCH_USER_DATA_ERROR = 'ASYNC_FETCH_USER_DATA_ERROR';
export const ASYNC_FETCH_USER_DATA_REQUEST = 'ASYNC_FETCH_USER_DATA_REQUEST';
